### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by homerlex** [AgoraIO-Community/Agora-RTM-Nodejs#1]
I'm trying to install this on Ubuntu 14.04

Using node version 8.10.0.

I am getting the following error when running `npm install`

```
> agora-node-rtm@1.0.0 install /home/vagrant/vagrant-workspace/Agora-RTM-Nodejs
> node-gyp rebuild

make: Entering directory `/home/vagrant/vagrant-workspace/Agora-RTM-Nodejs/build'
make: Warning: File `agorasdk.target.mk' has modification time 1.9 s in the future
  CXX(target) Release/obj.target/agorasdk/addon/node_uid.o
  CXX(target) Release/obj.target/agorasdk/addon/node_napi_api.o
  CXX(target) Release/obj.target/agorasdk/addon/node_async_queue.o
  CXX(target) Release/obj.target/agorasdk/addon/rtm_controller.o
In file included from ../addon/rtm_controller.cc:4:0:
../addon/rtm_controller.h:6:27: fatal error: event2/buffer.h: No such file or directory
 #include <event2/buffer.h>
                           ^
compilation terminated.
make: *** [Release/obj.target/agorasdk/addon/rtm_controller.o] Error 1
make: Leaving directory `/home/vagrant/vagrant-workspace/Agora-RTM-Nodejs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/vagrant/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 3.13.0-164-generic
gyp ERR! command "/home/vagrant/.nvm/versions/node/v8.10.0/bin/node" "/home/vagrant/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vagrant/vagrant-workspace/Agora-RTM-Nodejs
gyp ERR! node -v v8.10.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! agora-node-rtm@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the agora-node-rtm@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2019-07-12T12_08_04_139Z-debug.log
```

Any thoughts on how to resolve this?

**Comment by plutoless** [comment]
you are missing libevent, try installing it from apt-get

**Comment by homerlex** [comment]
Yup - that worked.  Now getting the following.  Is there a list of dependencies that need to be installed?

```
make: Entering directory `/home/vagrant/vagrant-workspace/Agora-RTM-Nodejs/build'
make: Warning: File `agorasdk.target.mk' has modification time 1.4 s in the future
  CXX(target) Release/obj.target/agorasdk/addon/node_uid.o
  CXX(target) Release/obj.target/agorasdk/addon/node_napi_api.o
  CXX(target) Release/obj.target/agorasdk/addon/node_async_queue.o
  CXX(target) Release/obj.target/agorasdk/addon/rtm_controller.o
In file included from ../addon/rtm_controller.cc:4:0:
../addon/rtm_controller.h:16:23: fatal error: uuid/uuid.h: No such file or directory
 #include <uuid/uuid.h>
```

**Comment by homerlex** [comment]
After installing uuid-dev I get this:

```
SOLINK_MODULE(target) Release/obj.target/agorasdk.node
/usr/bin/ld: cannot find -lagora_rtm_sdk
collect2: error: ld returned 1 exit status
make: *** [Release/obj.target/agorasdk.node] Error 1
make: Leaving directory `/home/vagrant/vagrant-workspace/Agora-RTM-Nodejs/build'
```

**Comment by homerlex** [comment]
OK, moving the libagora_rtm_sdk.so to /usr/lib/ solved that one.  I'll post more as I get other errors.

**Comment by homerlex** [comment]
Now I'm getting the following.  I thought perhaps it was because I did not have typescript installed but 
installing typescript (`npm install -g typescript`) did not resolve the problem.  What am I missing?
```
> agora-node-rtm@1.0.0 postinstall /home/vagrant/vagrant-workspace/Agora-RTM-Nodejs
> build:ts

sh: 1: build:ts: not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! agora-node-rtm@1.0.0 postinstall: `build:ts`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the agora-node-rtm@1.0.0 postinstall script
```

**Comment by plutoless** [comment]
just do npm build:ts and ignore the error

**Comment by homerlex** [comment]
Here is a recap of what I needed to do:
sudo apt-get install libevent-dev
sudo apt-get install uuid-dev
sudo cp libagora_rtm_sdk.so /usr/lib/ (this file is in the RTM Linux SDK)
npm install -g typescript
npm install
npm run build:ts

Thanks again for the help @plutoless

**Comment by zhangcunxiang** [comment]
I also come across all the errors upside can you team guys fix these issues ?

**Comment by plutoless** [comment]
not sure what you mean by fixing these issues. it should be working as long as you follow the steps above
