### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by fritzfr** [AgoraIO-Community/Agora-RTM-Nodejs#19]
Hey,

I'm trying to build this according to the readme. What I tried:

I cloned this repo.
I downloaded the Linux SDK v1.4.1 from here: https://download.agora.io/rtmsdk/release/Agora_RTM_SDK_for_Linux_v1_4_1.zip.
Then I copied `include/` and `libagora_rtm_sdk.so` into the folder.
`npm install` leads to this:

```
▶ npm install

> agora-node-rtm@1.0.0 install /Users/myUsername/Desktop/dev/Agora-RTM-Nodejs
> node-gyp rebuild

  CXX(target) Release/obj.target/agorasdk/addon/node_uid.o
  CXX(target) Release/obj.target/agorasdk/addon/log.o
  CXX(target) Release/obj.target/agorasdk/addon/syslog_log.o
  CXX(target) Release/obj.target/agorasdk/addon/node_napi_api.o
../addon/node_napi_api.cpp:20:45: error: too few arguments to function call,
      single argument 'isolate' was not specified
        return str.As<String>()->Utf8Length();
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Users/myUsername/Library/Caches/node-gyp/12.18.4/include/node/v8.h:2818:3: note:
      'Utf8Length' declared here
  int Utf8Length(Isolate* isolate) const;
  ^
../addon/node_napi_api.cpp:24:50: error: cannot initialize a parameter of type
      'v8::Isolate *' with an lvalue of type 'char *'
        int copied = str.As<String>()->WriteUtf8(buffer, len - 1, nullpt...
                                                 ^~~~~~
/Users/myUsername/Library/Caches/node-gyp/12.18.4/include/node/v8.h:2878:26: note:
      passing argument to parameter 'isolate' here
  int WriteUtf8(Isolate* isolate, char* buffer, int length = -1,
                         ^
../addon/node_napi_api.cpp:34:33: error: too few arguments to function call,
      single argument 'context' was not specified
    result = value->Uint32Value();
             ~~~~~~~~~~~~~~~~~~ ^
/Users/myUsername/Library/Caches/node-gyp/12.18.4/include/node/v8.h:2707:3: note:
      'Uint32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<uint32_t> Uint32Value(
  ^
/Users/myUsername/Library/Caches/node-gyp/12.18.4/include/node/v8config.h:368:31: note:
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../addon/node_napi_api.cpp:42:21: error: no matching member function for call to
      'BooleanValue'
    result = value->BooleanValue();
             ~~~~~~~^~~~~~~~~~~~
/Users/myUsername/Library/Caches/node-gyp/12.18.4/include/node/v8.h:2699:8: note:
      candidate function not viable: requires single argument 'isolate', but no
      arguments were provided
  bool BooleanValue(Isolate* isolate) const;
       ^
/Users/myUsername/Library/Caches/node-gyp/12.18.4/include/node/v8.h:2702:51: note:
      candidate function not viable: requires single argument 'context', but no
      arguments were provided
                V8_WARN_UNUSED_RESULT Maybe<bool> BooleanValue(
                                                  ^
../addon/node_napi_api.cpp:50:32: error: too few arguments to function call,
      single argument 'context' was not specified
    result = value->Int32Value();
             ~~~~~~~~~~~~~~~~~ ^
/Users/myUsername/Library/Caches/node-gyp/12.18.4/include/node/v8.h:2709:3: note:
      'Int32Value' declared here
  V8_WARN_UNUSED_RESULT Maybe<int32_t> Int32Value(Local<Context> context) const;
  ^
/Users/myUsername/Library/Caches/node-gyp/12.18.4/include/node/v8config.h:368:31: note:
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../addon/node_napi_api.cpp:59:33: error: too few arguments to function call,
      single argument 'context' was not specified
    result = value->NumberValue();
             ~~~~~~~~~~~~~~~~~~ ^
/Users/myUsername/Library/Caches/node-gyp/12.18.4/include/node/v8.h:2704:3: note:
      'NumberValue' declared here
  V8_WARN_UNUSED_RESULT Maybe<double> NumberValue(Local<Context> context) const;
  ^
/Users/myUsername/Library/Caches/node-gyp/12.18.4/include/node/v8config.h:368:31: note:
      expanded from macro 'V8_WARN_UNUSED_RESULT'
#define V8_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
                              ^
../addon/node_napi_api.cpp:128:20: warning: 'NewFromUtf8' is deprecated: Use
      maybe version [-Wdeprecated-declarations]
    return String::NewFromUtf8(isolate, value ? value : "");
                   ^
/Users/myUsername/Library/Caches/node-gyp/12.18.4/include/node/v8.h:3030:10: note:
      'NewFromUtf8' has been explicitly marked deprecated here
  static V8_DEPRECATED(
         ^
/Users/myUsername/Library/Caches/node-gyp/12.18.4/include/node/v8config.h:328:29: note:
      expanded from macro 'V8_DEPRECATED'
  declarator __attribute__((deprecated(message)))
                            ^
1 warning and 6 errors generated.
make: *** [Release/obj.target/agorasdk/addon/node_napi_api.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node@12/12.18.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command "/usr/local/Cellar/node@12/12.18.4/bin/node" "/usr/local/Cellar/node@12/12.18.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/myUsername/Desktop/dev/Agora-RTM-Nodejs
gyp ERR! node -v v12.18.4
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! agora-node-rtm@1.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the agora-node-rtm@1.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/myUsername/.npm/_logs/2020-10-08T08_44_05_676Z-debug.log
```

Any ideas?

**Comment by fritzfr** [comment]
Update:

The readme is lacking proper instructions. [This issue](https://github.com/AgoraIO-Community/Agora-RTM-Nodejs/issues/1) explains what to do, but is still missing the instruction to copy `IAgoraRtmService.h` into `addon/`.

I also don't understand why one needs to build this and why there are no builds included or available on npm or somewhere.
You can find my build here, in case you don't wanna build it yourself:
[dist.zip](https://github.com/AgoraIO-Community/Agora-RTM-Nodejs/files/5346740/dist.zip)
